server:
  port: 1010

spring:
  application:
    name: ms-discovery-serve

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:1010/eureka/